version: '3'
services: 
  db:
    image: mysql:latest
    ports:
      - 8001:3306
    volumes:
      - .:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: xxxx
    networks:
      - dbtoweb
  web:
    build: ./App
    stdin_open: True
    tty: True
    networks: 
      - dbtoweb
networks:
  dbtoweb:
    name: mywebapp_network1
    driver: bridge

